# Name and metadata of your task
task_name: 'AstroLink - Cryptoknight'
author: 'Amos'
markdownDescriptionPath: ""
description: "Leverage a powerful AI tool to spotlight the Koii ecosystem by running the AstroLink task. Help more people discover and join our growing community by engaging with targeted audiences and driving awareness through strategic interactions. A secondary X account is suggested to run this task. Before running the task, please ensure that you visit our discord https://discord.gg/mg3FCNyN and check the detail steps."
repositoryUrl: 'https://github.com/Amos0128/astrolink-marketing'
imageUrl: 'https://bafybeid4mlepkytklysae2mkyfj2js4k4sc5j7ctfb4xmhrabyjrwl7u6q.ipfs.w3s.link/Astro.png'
infoUrl: 'https://astrolink.market/'

# network value can be DEVELOPMENT , ARWEAVE or IPFS, Recommended IPFS when deploying to testnet as the cli automatically takes care of uploading the executable with the help of web3.js key
task_executable_network: 'IPFS'

# Path to your executable webpack if the selected network is IPFS and in  q case of DEVELOPMENT  name it as main
task_audit_program: 'dist/main.js'

# Total round time of your task : it must be given in slots and each slot is roughly equal to 408ms
round_time: 6000
audit_window: 2500
submission_window: 2500

# Amounts in KOII
minimum_stake_amount: 0.1

# total_bounty_amount cannot be grater than bounty_amount_per_round
# total bounty is not accepted in case of update task
total_bounty_amount: 10000
bounty_amount_per_round: 1000

#Number of times allowed to re-submit the distribution  list in case the distribution list is audited
allowed_failed_distributions: 1

#Space in MBs for the account size, that holds the task data
space: 0.1

# Note that the value field in RequirementTag is optional, so it is up to you to include it or not based on your use case.
# To add more global variables and task variables, please refer the type,value,description format shown below

requirementsTags:
  - type: TASK_VARIABLE
    value: 'TWITTER_USERNAME'
    description: 'The username of your volunteer Twitter account. Please ensure your volunteer Twitter account has passed the Twitter verification process.'
  - type: TASK_VARIABLE
    value: 'TWITTER_PASSWORD'
    description: 'The password of your volunteer Twitter account.'
  - type: TASK_VARIABLE
    value: 'TWITTER_VERIFICATION'
    description: 'If verification is required, will use your email or phone number to login.'
  - type: CPU
    value: '4-core'
  - type: RAM
    value: '5 GB'
  - type: STORAGE
    value: '5 GB'

## Task Bounty Type ##
# KOII or KPL
task_type: "KPL"

## Token Mint Address (ONLY for KPL tasks) ##
# The ASTRO Token address is provided as an example.
token_type: "CJLjkLohs3PScpBQ3r1WKHjQsWYPq291MgPjpTWTXNc4"

tags: ['Social Posting', 'AI']
environment: 'TEST'

# OPTIONAL Only provide the taskId if you are updating the task otherwise leave blank
task_id: 'AJrui23bRfvVWi5zBZfJNRBxhG2mTH5q4hJD4T6PC3YY'

# Provide the description for changes made in new version of task
migrationDescription: 'Fix reward amount'
